const ASMA_UL_HUSNA = [
  { number: 1, arabic: 'الرَّحْمَٰنُ', english: 'The Most Gracious', transliteration: 'Ar-Rahman', meaning: 'The Most Gracious' },
  { number: 2, arabic: 'الرَّحِيمُ', english: 'The Most Merciful', transliteration: 'Ar-Raheem', meaning: 'The Most Merciful' },
  { number: 3, arabic: 'الْمَلِكُ', english: 'The King', transliteration: 'Al-Malik', meaning: 'The King' },
  { number: 4, arabic: 'الْقُدُّوسُ', english: 'The Holy', transliteration: 'Al-Quddus', meaning: 'The Holy' },
  { number: 5, arabic: 'السَّلَامُ', english: 'The Source of Peace', transliteration: 'As-Salam', meaning: 'The Source of Peace' },
  { number: 6, arabic: 'الْمُؤْمِنُ', english: 'The Guardian of Faith', transliteration: 'Al-Mu\'min', meaning: 'The Guardian of Faith' },
  { number: 7, arabic: 'الْمُهَيْمِنُ', english: 'The Protector', transliteration: 'Al-Muhaymin', meaning: 'The Protector' },
  { number: 8, arabic: 'الْعَزِيزُ', english: 'The Almighty', transliteration: 'Al-Aziz', meaning: 'The Almighty' },
  { number: 9, arabic: 'الْجَبَّارُ', english: 'The Compeller', transliteration: 'Al-Jabbar', meaning: 'The Compeller' },
  { number: 10, arabic: 'الْمُتَكَبِّرُ', english: 'The Supreme', transliteration: 'Al-Mutakabbir', meaning: 'The Supreme' },
  { number: 11, arabic: 'الْخَالِقُ', english: 'The Creator', transliteration: 'Al-Khaliq', meaning: 'The Creator' },
  { number: 12, arabic: 'الْبَارِئُ', english: 'The Evolver', transliteration: 'Al-Bari', meaning: 'The Evolver' },
  { number: 13, arabic: 'الْمُصَوِّرُ', english: 'The Fashioner', transliteration: 'Al-Musawwir', meaning: 'The Fashioner' },
  { number: 14, arabic: 'الْغَفَّارُ', english: 'The Forgiver', transliteration: 'Al-Ghaffar', meaning: 'The Forgiver' },
  { number: 15, arabic: 'الْقَهَّارُ', english: 'The Subduer', transliteration: 'Al-Qahhar', meaning: 'The Subduer' },
  { number: 16, arabic: 'الْوَهَّابُ', english: 'The Bestower', transliteration: 'Al-Wahhab', meaning: 'The Bestower' },
  { number: 17, arabic: 'الرَّزَّاقُ', english: 'The Provider', transliteration: 'Ar-Razzaq', meaning: 'The Provider' },
  { number: 18, arabic: 'الْفَتَّاحُ', english: 'The Opener', transliteration: 'Al-Fattah', meaning: 'The Opener' },
  { number: 19, arabic: 'الْعَلِيمُ', english: 'The All-Knowing', transliteration: 'Al-Alim', meaning: 'The All-Knowing' },
  { number: 20, arabic: 'الْقَاضِي', english: 'The Judge', transliteration: 'Al-Qadir', meaning: 'The All-Powerful' },
  { number: 21, arabic: 'الْقَابِضُ', english: 'The Restrainer', transliteration: 'Al-Qabid', meaning: 'The Restrainer' },
  { number: 22, arabic: 'الْبَاسِطُ', english: 'The Reliever', transliteration: 'Al-Basit', meaning: 'The Reliever' },
  { number: 23, arabic: 'الْخَافِضُ', english: 'The Abaser', transliteration: 'Al-Khafid', meaning: 'The Abaser' },
  { number: 24, arabic: 'الرَّافِعُ', english: 'The Exalter', transliteration: 'Ar-Rafi', meaning: 'The Exalter' },
  { number: 25, arabic: 'الْمُعِزُّ', english: 'The Honorer', transliteration: 'Al-Muizz', meaning: 'The Honorer' },
  { number: 26, arabic: 'الْمُذِلُّ', english: 'The Humiliator', transliteration: 'Al-Muzill', meaning: 'The Humiliator' },
  { number: 27, arabic: 'السَّمِيعُ', english: 'The All-Hearing', transliteration: 'As-Sami', meaning: 'The All-Hearing' },
  { number: 28, arabic: 'الْبَصِيرُ', english: 'The All-Seeing', transliteration: 'Al-Basir', meaning: 'The All-Seeing' },
  { number: 29, arabic: 'الْحَكَمُ', english: 'The Judge', transliteration: 'Al-Hakam', meaning: 'The Judge' },
  { number: 30, arabic: 'الْعَدْلُ', english: 'The Just', transliteration: 'Al-Adl', meaning: 'The Just' },
  { number: 31, arabic: 'اللَّطِيفُ', english: 'The Subtle One', transliteration: 'Al-Latif', meaning: 'The Subtle One' },
  { number: 32, arabic: 'الْخَبِيرُ', english: 'The All-Aware', transliteration: 'Al-Khabir', meaning: 'The All-Aware' },
  { number: 33, arabic: 'الْحَلِيمُ', english: 'The Forbearing', transliteration: 'Al-Halim', meaning: 'The Forbearing' },
  { number: 34, arabic: 'الْعَظِيمُ', english: 'The Magnificent', transliteration: 'Al-Azim', meaning: 'The Magnificent' },
  { number: 35, arabic: 'الْغَفُورُ', english: 'The Forgiving', transliteration: 'Al-Ghafur', meaning: 'The Forgiving' },
  { number: 36, arabic: 'الشَّكُورُ', english: 'The Appreciative', transliteration: 'Ash-Shakur', meaning: 'The Appreciative' },
  { number: 37, arabic: 'الْعَلِيُّ', english: 'The Most High', transliteration: 'Al-Aliyy', meaning: 'The Most High' },
  { number: 38, arabic: 'الْكَبِيرُ', english: 'The Greatest', transliteration: 'Al-Kabir', meaning: 'The Greatest' },
  { number: 39, arabic: 'الْحَفِيظُ', english: 'The Preserver', transliteration: 'Al-Hafiz', meaning: 'The Preserver' },
  { number: 40, arabic: 'الْمُقِيتُ', english: 'The Sustainer', transliteration: 'Al-Muqit', meaning: 'The Sustainer' },
  { number: 41, arabic: 'الْحَسِيبُ', english: 'The Reckoner', transliteration: 'Al-Hasib', meaning: 'The Reckoner' },
  { number: 42, arabic: 'الْجَلِيلُ', english: 'The Majestic', transliteration: 'Al-Jalil', meaning: 'The Majestic' },
  { number: 43, arabic: 'الْكَرِيمُ', english: 'The Generous', transliteration: 'Al-Karim', meaning: 'The Generous' },
  { number: 44, arabic: 'الرَّقِيبُ', english: 'The Watchful', transliteration: 'Ar-Raqib', meaning: 'The Watchful' },
  { number: 45, arabic: 'الْمُجِيبُ', english: 'The Responder', transliteration: 'Al-Mujib', meaning: 'The Responder' },
  { number: 46, arabic: 'الْوَاسِعُ', english: 'The All-Encompassing', transliteration: 'Al-Wasi', meaning: 'The All-Encompassing' },
  { number: 47, arabic: 'الْحَكِيمُ', english: 'The Wise', transliteration: 'Al-Hakim', meaning: 'The Wise' },
  { number: 48, arabic: 'الْوَدُودُ', english: 'The Loving', transliteration: 'Al-Wadud', meaning: 'The Loving' },
  { number: 49, arabic: 'الْمَجِيدُ', english: 'The Glorious', transliteration: 'Al-Majid', meaning: 'The Glorious' },
  { number: 50, arabic: 'الْبَاعِثُ', english: 'The Resurrector', transliteration: 'Al-Baith', meaning: 'The Resurrector' },
  { number: 51, arabic: 'الشَّهِيدُ', english: 'The Witness', transliteration: 'Ash-Shahid', meaning: 'The Witness' },
  { number: 52, arabic: 'الْحَقُّ', english: 'The Truth', transliteration: 'Al-Haqq', meaning: 'The Truth' },
  { number: 53, arabic: 'الْوَكِيلُ', english: 'The Trustee', transliteration: 'Al-Wakil', meaning: 'The Trustee' },
  { number: 54, arabic: 'الْقَوِيُّ', english: 'The Strong', transliteration: 'Al-Qawwiyy', meaning: 'The Strong' },
  { number: 55, arabic: 'الْمَتِينُ', english: 'The Firm', transliteration: 'Al-Matin', meaning: 'The Firm' },
  { number: 56, arabic: 'الْوَلِيُّ', english: 'The Patron', transliteration: 'Al-Waliyy', meaning: 'The Patron' },
  { number: 57, arabic: 'الْحَمِيدُ', english: 'The Praiseworthy', transliteration: 'Al-Hamid', meaning: 'The Praiseworthy' },
  { number: 58, arabic: 'الْمُحْصِي', english: 'The Counter', transliteration: 'Al-Muhsi', meaning: 'The Counter' },
  { number: 59, arabic: 'الْمُبْدِئُ', english: 'The Originator', transliteration: 'Al-Mubdi', meaning: 'The Originator' },
  { number: 60, arabic: 'الْمُعِيدُ', english: 'The Restorer', transliteration: 'Al-Mu\'id', meaning: 'The Restorer' },
  { number: 61, arabic: 'الْمُحْيِي', english: 'The Giver of Life', transliteration: 'Al-Muhyiyy', meaning: 'The Giver of Life' },
  { number: 62, arabic: 'الْمُمِيتُ', english: 'The Giver of Death', transliteration: 'Al-Mumit', meaning: 'The Giver of Death' },
  { number: 63, arabic: 'الْحَيُّ', english: 'The Ever-Living', transliteration: 'Al-Hayy', meaning: 'The Ever-Living' },
  { number: 64, arabic: 'الْقَيُّومُ', english: 'The Sustainer', transliteration: 'Al-Qayyum', meaning: 'The Sustainer' },
  { number: 65, arabic: 'الْوَاجِدُ', english: 'The Finder', transliteration: 'Al-Wajid', meaning: 'The Finder' },
  { number: 66, arabic: 'الْمَاجِدُ', english: 'The Noble', transliteration: 'Al-Majid', meaning: 'The Noble' },
  { number: 67, arabic: 'الْوَاحِدُ', english: 'The One', transliteration: 'Al-Wahid', meaning: 'The One' },
  { number: 68, arabic: 'الصَّمَدُ', english: 'The Eternal', transliteration: 'As-Samad', meaning: 'The Eternal' },
  { number: 69, arabic: 'الْقَادِرُ', english: 'The Capable', transliteration: 'Al-Qadir', meaning: 'The Capable' },
  { number: 70, arabic: 'الْمُقْتَدِرُ', english: 'The Powerful', transliteration: 'Al-Muqtadir', meaning: 'The Powerful' },
  { number: 71, arabic: 'الْمُقَدِّمُ', english: 'The Expediter', transliteration: 'Al-Muqaddim', meaning: 'The Expediter' },
  { number: 72, arabic: 'الْمُؤَخِّرُ', english: 'The Delayer', transliteration: 'Al-Mu\'akhkhir', meaning: 'The Delayer' },
  { number: 73, arabic: 'الْأَوَّلُ', english: 'The First', transliteration: 'Al-Awwal', meaning: 'The First' },
  { number: 74, arabic: 'الْآخِرُ', english: 'The Last', transliteration: 'Al-Akhir', meaning: 'The Last' },
  { number: 75, arabic: 'الظَّاهِرُ', english: 'The Manifest', transliteration: 'Az-Zahir', meaning: 'The Manifest' },
  { number: 76, arabic: 'الْبَاطِنُ', english: 'The Hidden', transliteration: 'Al-Batin', meaning: 'The Hidden' },
  { number: 77, arabic: 'الْوَالِي', english: 'The Governor', transliteration: 'Al-Wali', meaning: 'The Governor' },
  { number: 78, arabic: 'الْمُتَعَالِي', english: 'The Exalted', transliteration: 'Al-Muta\'ali', meaning: 'The Exalted' },
  { number: 79, arabic: 'الْبَرُّ', english: 'The Pure', transliteration: 'Al-Barr', meaning: 'The Pure' },
  { number: 80, arabic: 'التَّوَّابُ', english: 'The Acceptor of Repentance', transliteration: 'At-Tawwab', meaning: 'The Acceptor of Repentance' },
  { number: 81, arabic: 'الْمُنْتَقِمُ', english: 'The Avenger', transliteration: 'Al-Muntaqim', meaning: 'The Avenger' },
  { number: 82, arabic: 'الْعَفُوُّ', english: 'The Pardoner', transliteration: 'Al-Afuww', meaning: 'The Pardoner' },
  { number: 83, arabic: 'الرَّؤُوفُ', english: 'The Kind', transliteration: 'Ar-Ra\'uf', meaning: 'The Kind' },
  { number: 84, arabic: 'مَالِكُ الْمُلْكِ', english: 'The King of Kings', transliteration: 'Malik-ul-Mulk', meaning: 'The King of Kings' },
  { number: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', english: 'The Lord of Majesty and Honor', transliteration: 'Dhul-Jalali wal-Ikram', meaning: 'The Lord of Majesty and Honor' },
  { number: 86, arabic: 'الْمُقْسِطُ', english: 'The Equitable', transliteration: 'Al-Muqsit', meaning: 'The Equitable' },
  { number: 87, arabic: 'الْجَامِعُ', english: 'The Gatherer', transliteration: 'Al-Jami', meaning: 'The Gatherer' },
  { number: 88, arabic: 'الْغَنِيُّ', english: 'The Self-Sufficient', transliteration: 'Al-Ghaniyy', meaning: 'The Self-Sufficient' },
  { number: 89, arabic: 'الْمُغْنِي', english: 'The Enricher', transliteration: 'Al-Mughni', meaning: 'The Enricher' },
  { number: 90, arabic: 'الْمَانِعُ', english: 'The Preventer', transliteration: 'Al-Mani', meaning: 'The Preventer' },
  { number: 91, arabic: 'الضَّارُّ', english: 'The Harmer', transliteration: 'Ad-Darr', meaning: 'The Harmer' },
  { number: 92, arabic: 'النَّافِعُ', english: 'The Benefiter', transliteration: 'An-Nafi', meaning: 'The Benefiter' },
  { number: 93, arabic: 'النُّورُ', english: 'The Light', transliteration: 'An-Nur', meaning: 'The Light' },
  { number: 94, arabic: 'الْهَادِي', english: 'The Guide', transliteration: 'Al-Hadi', meaning: 'The Guide' },
  { number: 95, arabic: 'الْبَدِيعُ', english: 'The Originator', transliteration: 'Al-Badi', meaning: 'The Originator' },
  { number: 96, arabic: 'الْبَاقِي', english: 'The Everlasting', transliteration: 'Al-Baqi', meaning: 'The Everlasting' },
  { number: 97, arabic: 'الْوَارِثُ', english: 'The Inheritor', transliteration: 'Al-Warith', meaning: 'The Inheritor' },
  { number: 98, arabic: 'الرَّشِيدُ', english: 'The Guide to Right Path', transliteration: 'Ar-Rashid', meaning: 'The Guide to Right Path' },
  { number: 99, arabic: 'الصَّبُورُ', english: 'The Patient', transliteration: 'As-Sabur', meaning: 'The Patient' },
];

export async function fetchAsmaUlHusna() {
  return { names: ASMA_UL_HUSNA };
}
